version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_web
    ports:
      - "85:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
