version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_web
    ports:
      - "4200:80"
    environment:
      URL_BASE_API: http://localhost:8000/api
      SECRET_API_KEY: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
